### ISSUE TITLE
if "team:read" is not present in the scope, authentification fail

### ISSUE THREAD

**Issue by remimeunier** [ueberauth/ueberauth_slack#20] opened 2017-04-19 14:31 UTC
The error is :
`
** (exit) an exception was raised:
(KeyError) key :slack_team not found in: %{ .....
.....
lib/ueberauth/strategy/slack.ex:165: Ueberauth.Strategy.Slack.extra/1
`

I saw you have a condition on this scope, but somehow it still try to access it. I don't really know where the problem come from.

**Comment by doomspork** [comment] 2018-01-19 16:30
This is a duplicate of #17

**Closed as completed by doomspork** 2018-01-19 16:30 UTC
